import "./global.css";
import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center min-h-screen bg-gray-100">
        <div className="rounded-2xl h-[80%] w-[90%] shadow-2xl bg-white">
          <header className="flex items-center rounded-t-2xl justify-center bg-[#2B4285] text-white h-20">
            <span className="text-5xl">🎬</span>
            <span className="ml-2 text-4xl font-bold">Movie Explorer</span>
          </header>

          {children}

          <footer className="flex justify-center items-center font-bold text-xl h-16">
            Built by 
            <Link 
              href="https://github.com/Boadu123/movie-explorer" 
              className="ml-2 text-blue-500"
            >
              @Benedict
            </Link>
          </footer>
        </div>
      </body>
    </html>

  )
}
